name: Build on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: 'Build Design system'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build
